# Generated by Django 5.1.2 on 2024-11-04 03:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('datetime_action', models.DateTimeField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
                ('datetime_action', models.DateTimeField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('foo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bars', to='testmodels.foo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
