# Generated by Django 5.1.2 on 2024-11-13 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='normal_bars',
            field=models.ManyToManyField(related_name='normal_foos', to='testmodels.bar'),
        ),
        migrations.CreateModel(
            name='SpecialFooBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_foo_bars', to='testmodels.bar')),
                ('foo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_foo_bars', to='testmodels.foo')),
            ],
        ),
        migrations.AddField(
            model_name='foo',
            name='special_bars',
            field=models.ManyToManyField(related_name='special_foos', through='testmodels.SpecialFooBar', to='testmodels.bar'),
        ),
    ]
